name: mcp-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  # ============================================================================
  # CORE UTILITIES (available via conda)
  # ============================================================================
  - requests>=2.31.0
  - pyyaml>=6.0
  - aiofiles>=23.0.0
  
  # ============================================================================
  # DEVELOPMENT TOOLS (available via conda)
  # ============================================================================
  - pytest>=7.4.0
  - black>=23.0.0
  - flake8>=6.1.0
  
  # ============================================================================
  # PIP DEPENDENCIES (not available or better via pip)
  # ============================================================================
  - pip:
    # Web Framework & API
    - fastapi>=0.104.0
    - uvicorn[standard]>=0.24.0
    - websockets>=12.0
    - pydantic>=2.5.0
    - jinja2>=3.1.0
    
    # Database & Storage
    - aiosqlite>=0.19.0
    
    # CLI & Utilities
    - click>=8.1.0
    - python-dotenv>=1.0.0
    - httpx>=0.25.0
    - python-multipart>=0.0.6
    
    # Development Tools
    - pytest-asyncio>=0.21.0
    - pytest-cov>=4.1.0
    - isort>=5.12.0
    - mypy>=1.7.0
    - pre-commit>=3.4.0